## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: GitHub Discussions
    url: https://github.com/algonius/algonius-browser/discussions
    about: For questions and discussions that don't belong in issues, please use our Discussions forum.
  - name: Discord Community
    url: https://discord.gg/NN3ABHggMK
    about: Chat with developers and users in our Discord community.
